apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Open Weather Map Service
  description: Open Weather Map Service Plugin for the Reekoh IoT Platform
  documentation: README.md
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Service
  price: 0
  tags:
    - service
    - open-weather
    - weather
  config:
    apiKey:
      label: API Key
      type: Password
      maxLength: 1000
      required: true
      help: API Key for the Open Weather Map API.
    requestType:
      label: Weather Request Type
      type: String
      maxLength: 1000
      required: true
      enum:
        - History
        - Current
        - Forecast Daily
        - Forecast 3 Hour
      help: Type of request to be sent to the API.
    locationType:
      label: Location Request Type
      type: String
      maxLength: 1000
      required: true
      enum:
        - City
        - City Id
        - Coordinates
      help: Type of location filter will be used to determine .

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    image: path/to/docker/image # ??